# Generated by Django 2.2.5 on 2019-09-23 04:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lte_integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_or_Cell_name', models.CharField(blank=True, max_length=10)),
                ('Service_type', models.CharField(blank=True, max_length=5)),
                ('task_type', models.CharField(blank=True, max_length=100)),
                ('task_details', models.CharField(blank=True, max_length=100)),
                ('execution_date', models.DateField(blank=True, default=datetime.datetime(2019, 9, 23, 4, 7, 17, 183360, tzinfo=utc))),
                ('Executor_name', models.CharField(blank=True, max_length=100)),
                ('Remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='lte_validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_or_Cell_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
