# Generated by Django 2.2.5 on 2019-09-24 04:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0003_auto_20190923_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lte_integration',
            name='execution_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 24, 4, 30, 55, 224940, tzinfo=utc)),
        ),
    ]
