# Generated by Django 2.2.5 on 2019-09-24 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0004_auto_20190924_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lte_integration',
            name='execution_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 24, 10, 36, 58, 418985, tzinfo=utc)),
        ),
    ]
