# Generated by Django 2.2.5 on 2019-09-25 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0005_auto_20190924_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lte_integration',
            old_name='Executor_name',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='lte_integration',
            old_name='task_details',
            new_name='executor',
        ),
        migrations.RenameField(
            model_name='lte_integration',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='lte_integration',
            old_name='Service_type',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='lte_integration',
            old_name='Site_or_Cell_name',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='lte_integration',
            old_name='task_type',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='lte_integration',
            name='execution_date',
        ),
        migrations.RemoveField(
            model_name='lte_validation',
            name='Assign',
        ),
        migrations.AddField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 25, 10, 17, 48, 735669, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='lte_integration',
            name='ticket',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lte_integration',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 25, 10, 17, 48, 735669, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='lte_validation',
            name='domain',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lte_validation',
            name='executor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lte_validation',
            name='ticket',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lte_validation',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
