# Generated by Django 2.2.5 on 2019-09-25 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0006_auto_20190925_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='lte_integration',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 25, 11, 31, 38, 311994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 25, 11, 31, 38, 311994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 25, 11, 31, 38, 311994, tzinfo=utc)),
        ),
    ]
