# Generated by Django 2.2.5 on 2019-09-25 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0007_auto_20190925_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 25, 11, 44, 47, 770705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 25, 11, 44, 47, 771705, tzinfo=utc)),
        ),
    ]
