# Generated by Django 2.2.5 on 2019-09-26 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0008_auto_20190925_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 26, 3, 24, 50, 741102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 9, 26, 3, 24, 50, 741102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 26, 3, 24, 50, 741102, tzinfo=utc)),
        ),
    ]
