# Generated by Django 2.2.5 on 2019-09-26 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0009_auto_20190926_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 26, 4, 58, 5, 746043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 4, 58, 5, 746043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 26, 4, 58, 5, 746043, tzinfo=utc)),
        ),
    ]
