# Generated by Django 2.2.5 on 2019-09-26 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0010_auto_20190926_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 26, 6, 23, 34, 373951, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 12, 23, 34, 373951)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 26, 6, 23, 34, 374951, tzinfo=utc)),
        ),
    ]
