# Generated by Django 2.2.5 on 2019-10-10 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0013_auto_20190926_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='lte_validation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 10, 11, 34, 22, 932274)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 10, 10, 11, 34, 22, 932274)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 10, 11, 34, 22, 933274)),
        ),
    ]
