# Generated by Django 2.2.5 on 2019-10-16 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0014_auto_20191010_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=300)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 16, 14, 55, 9, 64074)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 10, 16, 14, 55, 9, 64074)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 16, 14, 55, 9, 68074)),
        ),
    ]
