# Generated by Django 2.2.5 on 2019-10-16 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0015_auto_20191016_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Team'),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 16, 15, 17, 10, 672309)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 10, 16, 15, 17, 10, 672309)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 16, 15, 17, 10, 673309)),
        ),
    ]
