# Generated by Django 2.2.5 on 2019-10-22 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0017_auto_20191021_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='lte_validation',
            name='catag',
            field=models.CharField(blank=True, choices=[('1', 'Bulk'), ('2', 'Major'), ('3', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 22, 14, 53, 41, 86790)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 10, 22, 14, 53, 41, 86790)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 22, 14, 53, 41, 86790)),
        ),
    ]
