# Generated by Django 2.2.5 on 2019-11-24 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0018_auto_20191022_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='prs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_data', models.FileField(upload_to='PRS')),
                ('post_data', models.FileField(upload_to='PRS')),
                ('site_list', models.FileField(upload_to='PRS')),
                ('threshold', models.FileField(upload_to='PRS')),
                ('type', models.CharField(choices=[('1', '2G'), ('2', '3G'), ('3', '4G')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 24, 14, 9, 49, 591244)),
        ),
        migrations.AlterField(
            model_name='lte_integration',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 11, 24, 14, 9, 49, 591244)),
        ),
        migrations.AlterField(
            model_name='lte_validation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 24, 14, 9, 49, 592244)),
        ),
    ]
